In [3]:
import pandas as pd
import seaborn as sns
import sklearn as sk
import matplotlib.pyplot as plt

In [4]:
df = pd.read_excel('../data/Training.xlsx')

In [5]:
df.head()

,Match ID 18Char,Completion Date,Match Support Contact Notes,Stage,Little ID,Big ID,Big County,Big Age,Big Occupation,Big: Military,...,Little Contact: Interest Finder - Career,Little Contact: Interest Finder - Personality,Little Contact: Interest Finder - Three Wishes,Little Gender,Little Participant: Race/Ethnicity,Little Birthdate,Little Mailing Address Census Block Group,Big Home Census Block Group,Big Employer/School Census Block Group,Match Length
0,a1v2J0000028pRvQAI,2017-11-30,Question: Activities: Answer: See ms...,Closed,0032J00003PLe29QAD,0032J00003PhDOI,Hennepin,40,Unemployed,NaN,...,NaN,NaN,NaN,Female,Black or African American,2004-01-01,2.705303e+11,2.705302e+11,NaN,9.0
1,a1v2J0000028pRvQAI,2017-10-31,Question: Activities: Answer: See MS...,Closed,0032J00003PLe29QAD,0032J00003PhDOI,Hennepin,40,Unemployed,NaN,...,NaN,NaN,NaN,Female,Black or African American,2004-01-01,2.705303e+11,2.705302e+11,NaN,9.0
2,a1v2J0000028pRvQAI,2017-12-01,Question: Activities: Answer: Match ...,Closed,0032J00003PLe29QAD,0032J00003PhDOI,Hennepin,40,Unemployed,NaN,...,NaN,NaN,NaN,Female,Black or African American,2004-01-01,2.705303e+11,2.705302e+11,NaN,9.0
3,a1v2J0000028pRvQAI,2017-05-29,Question: Activities: Answer: Msc as...,Closed,0032J00003PLe29QAD,0032J00003PhDOI,Hennepin,40,Unemployed,NaN,...,NaN,NaN,NaN,Female,Black or African American,2004-01-01,2.705303e+11,2.705302e+11,NaN,9.0
4,a1v2J0000028pRvQAI,2017-04-30,Question: Activities: Answer: Msc as...,Closed,0032J00003PLe29QAD,0032J00003PhDOI,Hennepin,40,Unemployed,NaN,...,NaN,NaN,NaN,Female,Black or African American,2004-01-01,2.705303e+11,2.705302e+11,NaN,9.0

In [6]:
df.describe()

,Completion Date,Big Age,Big Approved Date,Big Birthdate,Match Activation Date,Match Closure Meeting Date,Big Assessment Uploaded,Big Acceptance Date,Big Days Acceptance to Match,Big Days Interview to Acceptance,...,Little RTBM in Matchforce,Little Moved to RTBM in MF,Little Application Received,Little Interview Date,Little Acceptance Date,Little Birthdate,Little Mailing Address Census Block Group,Big Home Census Block Group,Big Employer/School Census Block Group,Match Length
count,39198,39345.000000,35277,39345,39345,7362,14442,14442,7668.000000,14442.000000,...,14273.000000,14273.0,14273,14242,14258,39345,3.063100e+04,3.024300e+04,1.602000e+03,39345.000000
mean,2020-12-09 07:07:50.044390144,36.378828,2020-01-18 04:54:57.831448320,1988-03-25 22:42:42.134959936,2019-10-14 02:53:06.885245952,2020-05-17 22:27:05.427873024,2021-10-09 02:42:07.627752448,2021-11-21 09:03:06.954715648,144.016302,56.100679,...,0.023191,1.0,2021-05-30 20:23:41.537167872,2021-08-29 14:26:00.117960960,2021-10-04 00:45:39.009679104,2009-02-14 01:40:43.278688512,2.710549e+11,2.723587e+11,2.978464e+11,35.201388
min,2017-01-11 00:00:00,19.000000,2017-05-01 00:00:00,1944-04-01 00:00:00,2017-01-03 00:00:00,2017-05-01 00:00:00,2019-01-14 00:00:00,2019-02-20 00:00:00,-298.000000,0.000000,...,0.000000,1.0,2018-07-10 00:00:00,2018-08-22 00:00:00,2019-08-09 00:00:00,2000-09-01 00:00:00,2.700305e+11,6.037671e+10,5.001480e+10,0.000000
25%,2018-12-31 06:00:00,29.000000,2018-05-09 00:00:00,1984-08-01 00:00:00,2018-01-16 00:00:00,2018-10-23 06:00:00,2020-07-29 00:00:00,2020-08-26 00:00:00,37.000000,21.000000,...,0.000000,1.0,2020-03-09 00:00:00,2020-10-15 00:00:00,2020-11-04 00:00:00,2007-06-01 00:00:00,2.705302e+11,2.705302e+11,2.705302e+11,16.000000
50%,2020-09-23 00:00:00,33.000000,2019-08-16 00:00:00,1991-05-01 00:00:00,2019-05-14 00:00:00,2019-10-01 00:00:00,2021-06-21 00:00:00,2021-08-12 00:00:00,68.000000,32.000000,...,0.000000,1.0,2021-05-28 00:00:00,2021-07-31 12:00:00,2021-08-31 00:00:00,2008-12-01 00:00:00,2.705303e+11,2.705310e+11,2.705310e+11,29.700000
75%,2022-10-14 00:00:00,40.000000,2021-06-29 00:00:00,1995-07-01 00:00:00,2021-02-10 00:00:00,2021-08-22 00:00:00,2022-12-12 00:00:00,2023-02-13 00:00:00,154.000000,56.000000,...,0.000000,1.0,2022-06-06 00:00:00,2022-07-06 00:00:00,2022-08-22 00:00:00,2010-09-01 00:00:00,2.712303e+11,2.712303e+11,3.110900e+11,50.600000
max,2025-02-24 00:00:00,80.000000,2024-12-17 00:00:00,2005-04-01 00:00:00,2024-12-20 00:00:00,2025-02-06 00:00:00,2024-11-14 00:00:00,2025-01-09 00:00:00,1132.000000,1617.000000,...,1.000000,1.0,2024-11-07 00:00:00,2024-11-12 00:00:00,2024-11-12 00:00:00,2017-01-01 00:00:00,5.510912e+11,5.510912e+11,7.201330e+11,97.200000
std,NaN,10.996065,NaN,NaN,NaN,NaN,NaN,NaN,184.727275,107.437452,...,0.150514,0.0,NaN,NaN,NaN,NaN,9.605127e+09,2.769002e+10,1.070314e+11,23.385982

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39345 entries, 0 to 39344
Data columns (total 68 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Match ID 18Char                                    39345 non-null  object
 1   Completion Date                                    39198 non-null  datetime64[ns]
 2   Match Support Contact Notes                        37891 non-null  object
 3   Stage                                              39345 non-null  object
 4   Little ID                                          39345 non-null  object
 5   Big ID                                             39345 non-null  object
 6   Big County                                         32357 non-null  object
 7   Big Age                                            39345 non-null  int64
 8   Big Occupation                                     35996 non-null  object
 9   Big: Military                                      12661 non-null  object
 10  Big Approved Date                                  35277 non-null  datetime64[ns]
 11  Big Level of Education                             5740 non-null   object
 12  Big Languages                                      23200 non-null  object
 13  Big Gender                                         39333 non-null  object
 14  Big Birthdate                                      39345 non-null  datetime64[ns]
 15  Big Employer                                       33631 non-null  object
 16  Program                                            39345 non-null  object
 17  Program Type                                       39345 non-null  object
 18  Big Race/Ethnicity                                 39125 non-null  object
 19  Closure Reason                                     27434 non-null  object
 20  Closure Details                                    22240 non-null  object
 21  Match Activation Date                              39345 non-null  datetime64[ns]
 22  Match Closure Meeting Date                         7362 non-null   datetime64[ns]
 23  Rationale for Match                                35126 non-null  object
 24  Big Enrollment: Record Type                        14450 non-null  object
 25  Big Assessment Uploaded                            14442 non-null  datetime64[ns]
 26  Big Acceptance Date                                14442 non-null  datetime64[ns]
 27  Big Car Access                                     1067 non-null   object
 28  Big Days Acceptance to Match                       7668 non-null   float64
 29  Big Days Interview to Acceptance                   14442 non-null  float64
 30  Big Days Interview to Match                        7668 non-null   float64
 31  Big Open to Cross-Gender Match                     411 non-null    object
 32  Big Re-Enroll                                      14450 non-null  float64
 33  Big Contact: Preferred Communication Type          476 non-null    object
 34  Big Contact: Former Big/Little                     534 non-null    object
 35  Big Contact: Interest Finder - Sports              322 non-null    object
 36  Big Contact: Interest Finder - Places To Go        322 non-null    object
 37  Big Contact: Interest Finder - Hobbies             322 non-null    object
 38  Big Contact: Interest Finder - Entertainment       322 non-null    object
 39  Big Contact: Created Date                          14450 non-null  datetime64[ns]
 40  Big Enrollment: Created Date                       14450 non-null  datetime64[ns]
 41  Big Contact: Volunteer Availability                2648 non-null   object
 42  Big Contact: Marital Status                        13901 non-null  object
 43  Little RTBM Date in MF                             1308 non-null   datetime64[ns]
 44  Little RTBM in Matchforce                          14273 non-null  float64
 45  Little Moved to RTBM in MF                         14273 non-null  float64
 46  Little Application Received                        14273 non-null  datetime64[ns]
 47  Little Contact: Language(s) Spoken                 449 non-null    object
 48  Little Interview Date                              14242 non-null  datetime64[ns]
 49  Little Acceptance Date                             14258 non-null  datetime64[ns]
 50  Little Contact: Interest Finder - Sports           937 non-null    object
 51  Little Contact: Interest Finder - Outdoors         937 non-null    object
 52  Little Contact: Interest Finder - Arts             937 non-null    object
 53  Little Contact: Interest Finder - Places To Go     937 non-null    object
 54  Little Contact: Interest Finder - Hobbies          937 non-null    object
 55  Little Contact: Interest Finder - Entertainment    937 non-null    object
 56  Little Contact: Interest Finder - Other Interests  328 non-null    object
 57  Little Other Interests                             4006 non-null   object
 58  Little Contact: Interest Finder - Career           862 non-null    object
 59  Little Contact: Interest Finder - Personality      937 non-null    object
 60  Little Contact: Interest Finder - Three Wishes     862 non-null    object
 61  Little Gender                                      39337 non-null  object
 62  Little Participant: Race/Ethnicity                 38563 non-null  object
 63  Little Birthdate                                   39345 non-null  datetime64[ns]
 64  Little Mailing Address Census Block Group          30631 non-null  float64
 65  Big Home Census Block Group                        30243 non-null  float64
 66  Big Employer/School Census Block Group             1602 non-null   float64
 67  Match Length                                       39345 non-null  float64
dtypes: datetime64[ns](14), float64(10), int64(1), object(43)
memory usage: 20.4+ MB